# Generated by Django 5.0.6 on 2026-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
